

name: Actions-nginx


on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: artemsavchuk94/nginx-actions
          
          registry: docker.io
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
          
          
          
          
