

name: Actions-nginx


on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - name: Application Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          change_path: "src/service"
      - name: Database Version
        id: db-version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          major_pattern: "(MAJOR-DB)"
          minor_pattern: "(MINOR-DB)"
          change_path: "src/migrations"
          namespace: db
   
   
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: artemsavchuk94/nginx-actions
          tags: v1.0.0 , latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
          
          
          
          
